### PR TITLE
internationalization

### PR DESCRIPTION
**Pull request by taylorjb**
- using build plugin untra/polyglot
- lang chooser dropdown in main navigation
- translation of about page

### CODE REVIEW

**Comment by taylorjb** [comment]
One concern is `Jekyll::Site.process` is overridden by the plugin so future plugins that also override this could be affected.

**Comment by CodeShark** [comment]
@taylorjb Thanks, taking a look.
@Excellion1 ^

**Comment by taylorjb** [comment]
#7 needs to be resolved before merging this.

**Comment by taylorjb** [comment]
Preview is working. This PR changes can be viewed here: https://taylorjb.github.io/chainsplit.github.io/

**Comment by CodeShark** [comment]
Could we bother you to add some actual Spanish text to the preview? Just a couple phrases will do.

**Pull request merged**
