### PR TITLE
Bitcoin forks & forks-of-forks

### PR DESCRIPTION
**Pull request by brinkt**
- Table of known Bitcoin forks & forks-of-forks
- Fork page w/ info & external links
- Code collaboration w/ @FeedTheWeb

### CODE REVIEW

**Comment by brinkt** [comment]
Preview has been built to dev mirror: https://chainsplit.github.io/chainsplit-www/

**Comment by nothingmuch** [comment]
The information about clashic & cash is slightly misleading, since technically clashic has replay protection with respect to bitcoin, and cash does not have replay protection with respect to clashic, I think this nuance should be conveyed in more than just a binary yes/no, since its ambiguous - the table is displaying 1 binary attribute per form, but this is really just one column in a sparse matrix of all the possible forks, as possibility of replay is a pairwise relation. I think that the main table should still be largely oriented with respect to just bitcoin, but that saying just yes/no without qualifying that it's more complicated that that might introduce confusion. In the spreadsheet I put this down as "yes (bitcoin) no (cash)" and "no (clashic) yes (bitcoin)" for clashic and cash respectively.

**Comment by CodeShark** [comment]
@nothingmuch: On point. Can we define rp protection as only being wrt parent branch?

**Comment by CodeShark** [comment]
Should we have two columns for rp protection one wrt parent, another wrt bitcoin?

**Comment by nothingmuch** [comment]
Yes, I like this, it'll only need to be revised once clashic starts treating future bcash hard forks as a [stochastic layer 2 upgrade](
https://twitter.com/_GIBUS_/status/931698926004129793) ;-)

**Comment by sunnankar** [comment]
This is looking very helpful so far.

**Comment by tpmccallum** [comment]
This looks good. Very informative. Also really like how all links to external fork sites open in a new tab.

**Comment by tpmccallum** [comment]
Do we need to change the text from 
"A known list of Bitcoin forks, including forks-of-forks."
to
"A **list** of **known** bitcoin **hard** forks, including forks-of-forks."

**Comment by 10b01b01b10b** [comment]
Shouldn't the column header "Fork height" be labelled "Block height"?

**Pull request merged**
